language: java
jdk: openjdk23

# Configuração do sistema operacional
os: linux
dist: focal

# Dá permissão de execução ao Gradle Wrapper
before_install:
  - chmod +x gradlew

# Etapas de build e execução dos testes
script:
  - ./gradlew clean build
  - ./gradlew test

# Configuração de cache para economizar tempo nos próximos builds
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Especifica a branch para rodar os builds
deploy:
  on:
    branch: main

# Notificações de build por e-mail
notifications:
  email:
    recipients:
      - $EMAILID
    on_success: never
    on_failure: always
