on:
  push:
    branches:
      - main

language: java
jdk: openjdk23

os: linux
dist: focal

before_install:
	- chmod +x gradlew

script:
	- ./gradlew test
	- ./gradlew clean build

cache:
	directories:
		- $HOME/.gradle/caches/
		- $HOME/.gradle/wrapper/

notifications:
	email:
		recipients:
			- $EMAILID
		on_sucess: never
		on_failure: always
